# name: Update gist with RescueTime stats
# on:
#   schedule:
#     - cron: '0 1 * * *'
# jobs:
#   update-gist:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - name: Update gist
#         uses: jetaimefrc/waka-box-productivity@master
#         env:
#           GH_TOKEN: ${{ secrets.GH_TOKEN }}
#           GIST_ID: ${{ secrets.GIST_ID }}
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
